#!/bin/sh

export GOPATH=`pwd`/Godeps/_workspace:$GOPATH

version=`grep currentVersion main.go | head -n 1 | cut -d\" -f2`

git tag v$version

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o gh-downloader-linux-amd64 .
GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o gh-downloader-darwin-amd64 .

hub release create -a gh-downloader-linux-amd64 -a gh-downloader-darwin-amd64 v$version

rm gh-downloader-*
