name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: go test -v ./...
  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: test
    permissions:
      contents: write
    if: contains('refs/heads/master', github.ref)
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Bump version
        id: bump-version
        uses: upfluence/actions/bump-version@master
      - name: Compile binaries
        uses: upfluence/actions/compile-go@master
        with:
          executable-paths: ./cmd/gh-downloader
          linker-mode: cli
          dist-dir: dist/
          version: ${{ steps.bump-version.outputs.version }}
          os: linux,darwin
          arch: amd64,arm64
          name-template: '{{ .Name }}-{{ .OS }}-{{ .Arch }}'
      - name: Create release
        uses: upfluence/actions/create-github-release@master
        with:
          attachments: dist/*
          version: ${{ steps.bump-version.outputs.version }}
